const MISAResource = {
    VN: {
        Title: 'MISAEShop',
        ProductName: 'Kế toán',
        CompanyName: 'Công ty cổ phần MISA',
        ErrorMisaAlert: 'Lỗi liên hệ với misa để xử lý.',
        SideBar: {
            Home: 'Trang chủ',
            Employee: 'Nhân viên',
            Customer: 'Khách hàng',
            Product: 'Sản phẩm',
            Report: 'Báo cáo',
            CloseSidebar: 'Thu gọn',
            Department: 'Đơn vị',
            Position: 'Vị trí',
            Inventory: 'Hàng hóa',
        },
        Manage: {
            EmployeeInfo: {
                InputSearch: 'Tìm theo mã, tên, số điện thoại',
                Name: 'Nhân viên',
                EmployeeCode: 'Mã nhân viên',
                Id: 'Mã',
                FullName: 'Họ và tên',
                DateOfBirth: 'Ngày sinh',
                Gender: 'Giới tính',
                Email: 'Email',
                Department: {
                    Name: 'Đơn vị',
                    Empty: 'Chọn đơn vị',
                },
                Position: {
                    Name: 'Chức danh',
                    Empty: 'Chọn chức danh',
                },
                IdentityNumber: 'Số CMND',
                IdentityDate: 'Ngày Cấp',
                IdentityPlace: 'Nơi cấp',
                Address: 'Địa chỉ',
                PhoneNumberForm: 'DT di động',
                PhoneNumber: 'SĐT',
                Customer: 'Là khách hàng',
                Provider: 'Là nhà cung cấp',
                LandlinePhone: 'DT cố định',
                BankAccount: 'Tài khoản ngân hàng',
                BankName: 'Tên ngân hàng',
                BankBranch: 'Chi nhánh ngân hàng',
            },
            CustomerInfo: {
                Name: 'Khách hàng',
            },
            DepartmentInfo: {
                Name: 'Đơn vị',
                InputSearch: 'Tìm theo mã, tên đơn vị',
                DepartmentCode: 'Mã đơn vị',
                DepartmentName: 'Tên đơn vị',
                Description: 'Mô tả',
            },
            PositionInfo: {
                Name: 'Vị trí',
                InputSearch: 'Tìm theo mã, tên vị trí',
                PositionCode: 'Mã vị trí',
                PositionName: 'Tên vị trí',
                Description: 'Mô tả',
            },
        },
        FormTitle: {
            Employee: {
                Add: 'Thêm mới nhân viên',
                Update: 'Thông tin nhân viên',
            },
            Department: {
                Add: 'Thêm mới đơn vị',
                Update: 'Thông tin đơn vị',
            },
            Position: {
                Add: 'Thêm mới vị trí',
                Update: 'Thông tin vị trí',
            },
            Inventory: {
                Add: 'Thêm mới',
                Update: 'Sửa',
            },
        },
        Gender: {
            Male: 'Nam',
            Female: 'Nữ',
            Other: 'Khác',
        },
        EmployeeInvalidError: {
            EmployeeCodeEmpty: 'Mã không được để trống.',
            EmployeeCodeFormat: 'Mã không đúng định dạng.',
            EmployeeCodeMaxLength: 'Mã không quá @number ký tự.',
            EmployeeDuplicateCode: 'Mã nhân viên bị trùng',
            FullNameEmpty: 'Họ và tên không được để trống.',
            FullNameMaxLength: 'Họ và tên không quá @number ký tự.',
            EmailFormat: 'Email không đúng định dạng.',
            EmailEmpty: 'Email không được để trống.',
            EmailMaxLength: 'Email không quá @number ký tự.',
            IdentityNumberMaxLength: 'Số CMND không quá @number ký tự',
            PhoneNumberMaxLength: 'Số điệnt thoại không quá @number ký tự.',
            LandLinePhoneMaxLength: 'DT cố định không quá @number ký tự.',
            BankAccountMaxLength: 'Số tài khoản không quá @number ký tự.',
            DepartmentEmpty: 'Đơn vị không được để trống.',
            IdentityPlaceMaxLength: 'Nơi cấp khống quá @number ký tự.',
            AddressMaxLength: 'Địa chỉ không quá @number ký tự.',
            BankNameMaxLength: 'Tên ngân hàng không quá @number ký tự.',
            BankBranchMaxLength: 'Chi nhánh không quá @number ký tự.',
        },
        DepartmentInvalidError: {
            DepartmentCodeEmpty: 'Mã không được để trống.',
            DepartmentCodeMaxLength: 'Mã không quá @number ký tự.',
            DepartmentCodeFormat: 'Mã không đúng định dạng.',
            DepartmentNameEmpty: 'Tên đơn vị không được để trống.',
            DepartmentNameMaxLength: 'Tên đơn vị không quá @number ký tự.',
            DescriptionMaxLength: 'Mô tả không quá @number ký tự.',
        },
        PositionInvalidError: {
            PositionCodeEmpty: 'Mã không được để trống.',
            PositionCodeMaxLength: 'Mã không quá @number ký tự.',
            PositionCodeFormat: 'Mã không đúng định dạng.',
            PositionNameEmpty: 'Tên vị trí không được để trống.',
            PositionNameMaxLength: 'Tên vị trí không quá @number ký tự.',
            DescriptionMaxLength: 'Mô tả không quá @number ký tự.',
        },
        Toast: {
            Title: {
                Info: 'Thông tin!',
                Success: 'Thành công!',
            },
            Icon: {
                success: 'success',
            },
            Success: {
                Add: 'Thêm mới thành công',
                Update: 'Sửa thành công',
                Delete: 'Xóa thành công',
            },
            Undo: 'Hoàn tác',
        },
        Dialog: {
            Icon: {
                warning: 'warning',
                success: 'success',
            },
            Button: {
                Delete: 'Xóa',
                Close: 'Đóng',
                Cancel: 'Hủy',
                Yes: 'Có',
                No: 'Không',
            },

            DeleteEmployee: {
                Title: 'Xóa nhân viên?',
                DeleteContent: 'Bạn có thực sự muốn xóa nhân viên <EmployeeCode>?',
                DeleteListContent: 'Bạn có thực sự muốn xóa danh sách nhân viên đã chọn?',
            },
            DeleteDepartment: {
                Title: 'Xóa đơn vị?',
                DeleteContent: 'Bạn có thực sự muốn xóa đơn vị <DepartmentCode>?',
                DeleteListContent: 'Bạn có thực sự muốn xóa danh sách đơn vị đã chọn?',
            },
            DeletePosition: {
                Title: 'Xóa vị trí?',
                DeleteContent: 'Bạn có thực sự muốn xóa vị trí <PositionCode>?',
                DeleteListContent: 'bạn có thực sự muốn xóa danh sách vị trí đã chọn?',
            },
            Warning: {
                Title: 'Có lỗi!',

                Validate: {
                    Title: 'Thông tin không hợp lệ!',
                },
                ChangeForm: {
                    Title: 'Có sự thay đổi!',
                    Content: 'Dữ liệu bị thay đổi. Bạn có muốn cất không?',
                },
            },
        },
        Button: {
            AddEmployee: 'Thêm mới nhân viên',
            AddDepartment: 'Thêm mới đơn vị',
            AddPosition: 'Thêm mới vị trí',
            Delete: 'Xóa',
            Close: 'Đóng',
            Cancel: 'Hủy bỏ',
            Yes: 'Có',
            No: 'Không',
            UnChecked: 'Bỏ chọn',
            Add: 'Thêm mới',
            Save: 'Lưu',
            SaveAdd: 'Lưu và thêm mới',
            Selected: 'Đã chọn',
            UnSelected: 'Bỏ chọn',
            ExportExcel: 'Xuất Excel',
            ImportExcel: 'Nhập Excel',
            DefaultTable: 'Lấy mẫu mặc định',
            SaveSetting: 'Lưu',
            ChooseExcelFile: 'Chọn file exce',
            ExportAll: 'Xuất tất cả',
            ExportSelected: 'Xuất theo danh sách chọn',
            ExportSearch: 'Xuất theo bản ghi tìm kiếm',
            Filter: 'Áp dụng',
            UnFilter: 'Bỏ lọc',
            Replication: 'Nhân bản',
            Edit: 'Sửa',
            Reset: 'Nạp',
            Setting: 'Tiện ích',
            SaveAndReplication: 'Lưu và nhân bản',
        },

        Table: {
            InputSearch: 'Tìm kiếm trong trang',
            InputSearchColumn: 'Tìm kiếm',
            Total: 'Tổng',
            Record: 'kết quả',
            Page: 'bản ghi trên 1 trang',
            Next: 'Sau',
            Prev: 'Trước',
            NoData: 'Không có dữ liệu',
            SettingTable: 'Tùy Chỉnh cột',
            Show: 'Hiển thị',
            OutOf: 'trên',
            Action: {
                Name: 'Hành động',
                Edit: 'Sửa',
                Add: 'Thêm',
                Delete: 'Xóa',
                Duplicate: 'Nhân bản',
                DiscontinueUse: 'Ngưng sử dụng',
            },
            Filter: {
                Notequal: ' ≠ : Khác',
                Notcontain: ' ! : Không chứa',
                Equal: ' = : Bằng',
                NotEqual: ' ≠ : Khác',
                Contain: ' * : Chứa',
                NotContain: ' ! : Không chứa',
                Greater: ' > : Lớn hơn',
                Smaller: ' < : Nhỏ hơn',
                Condition: 'Điều kiện lọc',
                ValueFilter: 'Giá trị lọc',
                ValueFilterInput: 'Nhập giá trị lọc',
            },
        },
        CreatedDate: 'Ngày tạo',
        Tooltip: {
            PhoneNumber: 'Số điện thoại',
            IdentityNumber: 'Căn Cước Công Dân',
            ExportExcel: 'Xuất Excel',
            ImportExcel: 'Nhập Excel',
            SettingTable: 'Cài đặt',
            Pin: 'Ghim',
            Drag: 'Đổi cột',
            ResetData: 'Load toàn bộ dữ liệu',
        },
        DatePicker: {
            Today: 'Hôm nay',
            Mo: 'T2',
            Tu: 'T3',
            We: 'T4',
            Th: 'T5',
            Fr: 'T6',
            Sa: 'T7',
            Su: 'CN',
            Jan: 'Tháng 1',
            Feb: 'Tháng 2',
            Mar: 'Tháng 3',
            Apr: 'Tháng 4',
            May: 'Tháng 5',
            Jun: 'Tháng 6',
            Jul: 'Tháng 7',
            Aug: 'Tháng 8',
            Sep: 'Tháng 9',
            Oct: 'Tháng 10',
            Nov: 'Tháng 11',
            Dec: 'Tháng 12',
        },
        Excel: {
            Employee: {
                Title: 'Danh sách nhân viên',
                Sheet: 'Danh sách nhân viên',
                FileName: 'Danh_sach_nhan_vien.xlsx',
            },
            Department: {
                Title: 'Danh sách đơn vị',
                Sheet: 'Danh sách đơn vị',
                FileName: 'Danh_don_vi_vien.xlsx',
            },
            Position: {
                Title: 'Danh sách vị trí',
                Sheet: 'Danh sách vị trí',
                FileName: 'Danh_vi_tri_vien.xlsx',
            },
        },
        KeyName: {
            EmployeeCode: 'Mã nhân viên',
            Id: 'Mã',
            FullName: 'Họ và tên',
            DateOfBirth: 'Ngày sinh',
            Gender: 'Giới tính',
            Email: 'Email',
            DepartmentName: 'Đơn vị',
            PositionName: 'Chức danh',
            IdentityNumber: 'Số CMND',
            IdentityDate: 'Ngày Cấp',
            IdentityPlace: 'Nơi cấp',
            Address: 'Địa chỉ',
            PhoneNumberForm: 'DT di động',
            PhoneNumber: 'SĐT',
            Customer: 'Là khách hàng',
            Provider: 'Là nhà cung cấp',
            LandlinePhone: 'DT cố định',
            BankAccount: 'Tài khoản ngân hàng',
            BankName: 'Tên ngân hàng',
            BankBranch: 'Chi nhánh ngân hàng',
        },
    },
    EN: {
        Title: 'MISAEShop',
        ProductName: 'Accounting',
        CompanyName: 'MISA Joint Stock Company',
        ErrorMisaAlert: 'An error occurred! please contact MISA.',
        SideBar: {
            Home: 'Home',
            Employee: 'Employee',
            Customer: 'Customer',
            Product: 'Product',
            Report: 'Report',
            CloseSidebar: 'Close sidebar',
            Department: 'Department',
            Position: 'Position',
            Inventory: 'Inventory',
        },
        Manage: {
            EmployeeInfo: {
                Name: 'Employee',
                InputSearch: 'Search by code, name, phone number',
                EmployeeCode: 'Employee Code',
                Id: 'Code',
                FullName: 'Full Name',
                DateOfBirth: 'Date of Birth',
                Gender: 'Gender',
                Email: 'Email',
                Department: {
                    Name: 'Department',
                    Empty: 'Select department',
                },
                Position: {
                    Name: 'Position',
                    Empty: 'Select position',
                },
                IdentityNumber: 'Identity Number',
                IdentityDate: 'Date of Issue',
                IdentityPlace: 'Place of Issue',
                Address: 'Address',
                PhoneNumberForm: 'Mobile Phone',
                PhoneNumber: 'Mobile Phone',
                Customer: 'Customer',
                Provider: 'Provider',
                LandlinePhone: 'Landline Phone',
                BankAccount: 'Bank Account',
                BankName: 'Bank Name',
                BankBranch: 'Bank Branch',
            },
            CustomerInfo: {
                Name: 'Customer',
            },
            DepartmentInfo: {
                Name: 'Department',
                InputSearch: 'Search by code, department name',
                DepartmentCode: 'Department Code',
                DepartmentName: 'Department Name',
                Description: 'Description',
            },
            PositionInfo: {
                Name: 'Position',
                InputSearch: 'Search by code, position name',
                PositionCode: 'Position Code',
                PositionName: 'Position Name',
                Description: 'Description',
            },
        },
        FormTitle: {
            Add: 'Add new @object',
            Update: '@object information',
            Employee: {
                Add: 'Add new Employee',
                Update: 'Employee information',
            },
            Department: {
                Add: 'Add new department',
                Update: 'Department information',
            },
            Position: {
                Add: 'Add new position',
                Update: 'Position information ',
            },
            Inventory: {
                Add: 'Add',
                Update: 'Edit',
            },
        },
        Gender: {
            Male: 'Male',
            Female: 'Female',
            Other: 'Other',
        },
        EmployeeInvalidError: {
            EmployeeCodeEmpty: 'Employee Code Not Empty.',
            EmployeeCodeFormat: 'Employee Code Invalid.',
            EmployeeCodeMaxLength: 'Code limit: @number characters.',
            EmployeeDuplicateCode: 'Dublicate Code Employee',
            FullNameEmpty: 'Full Name Not Empty.',
            FullNameMaxLength: 'Full Name limit: @number characters.',
            EmailFormat: 'Email Invalid.',
            EmailEmpty: 'Email Not Empty.',
            EmailMaxLength: 'Email limit: @number characters',
            IdentityNumberMaxLength: 'Identity number limit: @number characters.',
            PhoneNumberMaxLength: 'Phone number limit: @number characters.',
            LandLinePhoneMaxLength: 'LandLine Phone limit: @number characters.',
            BankAccountMaxLength: 'Bank Account limit: @number characters.',
            DepartmentEmpty: 'Department Not Empty.',
            IdentityPlaceMaxLength: 'Identity Place limit: @number characters.',
            AddressMaxLength: 'Address limit: @number characters.',
            BankNameMaxLength: 'Bank Name limit: @number characters.',
            BankBranchMaxLength: 'Bank Branch limit: @number characters.',
        },
        DepartmentInvalidError: {
            DepartmentCodeEmpty: 'Department Code Not Empty.',
            DepartmentCodeFormat: 'Department Code Invalid.',
            DepartmentCodeMaxLength: 'Department Code limit: @number characters.',
            DepartmentNameEmpty: ' Department Name Not Empty.',
            DepartmentNameMaxLength: ' Department Name limit: @number characters.',
            DescriptionMaxLength: 'Description limit: @number characters.',
        },
        PositionInvalidError: {
            PositionCodeEmpty: 'Position Code Code Not Empty.',
            PositionCodeMaxLength: 'Position Code limit: @number characters.',
            PositionCodeFormat: 'Position Code Invalid.',
            PositionNameEmpty: 'Position Name Not Empty.',
            PositionNameMaxLength: 'Position Name limit: @number characters.',
            DescriptionMaxLength: 'Description limit: @number characters.',
        },
        Toast: {
            Title: {
                Info: 'Information!',
                Success: 'Success!',
            },
            Icon: {
                success: 'success',
            },
            Content: {
                Add: 'Add successfully',
                Update: 'Update successfully',
                Delete: 'Delete successfully',
            },
            Success: {
                Add: 'Add successfully',
                Update: 'Update successfully',
                Delete: 'Delete successfully',
            },
            Undo: 'Undo',
        },
        Dialog: {
            Icon: {
                warning: 'warning',
                success: 'success',
            },
            DeleteEmployee: {
                Title: 'Delete employee?',
                DeleteContent: 'Do you want to delete employee <EmployeeCode>?',
                DeleteListContent: 'Do you want to delete the selected employees?',
            },
            DeleteDepartment: {
                Title: 'Delete department?',
                DeleteContent: 'Do you want to delete department <DepartmentCode>?',
                DeleteListContent: 'Do you want to delete the selected department?',
            },
            DeletePosition: {
                Title: 'Delete position?',
                DeleteContent: 'Do you want to delete position <PositionCode>?',
                DeleteListContent: 'Do you want to delete the selected position?',
            },
            Warning: {
                Title: 'Error!',

                Validate: {
                    Title: 'Invalid information!',
                },
                ChangeForm: {
                    Title: 'Changes detected!',
                    Content: 'Data has been changed. Do you want to save?',
                },
            },
            Button: {
                Delete: 'Delete',
                Close: 'Close',
                Cancel: 'Cancel',
                Yes: 'Yes',
                No: 'No',
            },
        },
        Button: {
            AddEmployee: 'Add Employee',
            AddDepartment: 'Add Department',
            AddPosition: 'Add Position',
            Delete: 'Delete',
            Close: 'Close',
            Cancel: 'Cancel',
            Yes: 'Yes',
            No: 'No',
            UnChecked: 'UnChecked',
            Add: 'Add New',
            SaveAdd: 'Save and Continue',
            Save: 'Save',
            Selected: 'Checked',
            UnSelected: 'Un checked',
            ExportExcel: 'Export Excel',
            ImportExcel: 'Import Excel',
            DefaultTable: 'Get Default',
            SaveSetting: 'Save',
            ChooseExcelFile: 'Choose Excel File',
            ExportAll: 'Export All',
            ExportSelected: 'Export Selected Items',
            ExportSearch: 'Export Search Results',
            Filter: 'Filter',
            UnFilter: 'Unfiltered',
            Replication: 'Replication',
            Edit: 'Edit',
            Reset: 'Reset',
            Setting: 'Setting',
            SaveAndReplication: 'Save And Replication',
        },

        Table: {
            InputSearch: 'search in list',
            InputSearchColumn: 'search column',
            Total: 'Total',
            Record: 'record',
            Page: 'records per page',
            SettingTable: 'Setting column',
            NoData: 'No data',
            Show: 'Show',
            OutOf: 'out of',
            Action: {
                Name: 'Action',
                Edit: 'Edit',
                Add: 'Add',
                Delete: 'Delete',
                Duplicate: 'Duplicate',
                DiscontinueUse: 'Discontinue use',
            },
            Next: 'next',
            Prev: 'prev',
            Filter: {
                Notequal: ' ≠ : NotEqual',
                Notcontain: ' ! : NotContain',
                Equal: ' = : Equal',
                NotEqual: ' ≠ : NotEqual',
                Contain: ' * : Contain',
                NotContain: ' ! : NotContain',
                Greater: ' > : Greater',
                Smaller: ' < : Smaller',
                Condition: 'Filteration condition',
                ValueFilter: 'filteration value',
                ValueFilterInput: 'Enter filter value',
            },
        },
        CreatedDate: 'Created Date',
        Tooltip: {
            PhoneNumber: '',
            IdentityNumber: '',
            ExportExcel: 'Export Excel',
            ImportExcel: 'Import Excel',
            SettingTable: 'Setting Table',
            Pin: 'Pin Table',
            Drag: 'Drag',
            ResetData: 'Reset',
        },
        DatePicker: {
            Today: 'Today',
            Mo: 'Mon',
            Tu: 'Tue',
            We: 'Wed',
            Th: 'Thu',
            Fr: 'Fri',
            Sa: 'Sat',
            Su: 'Sun',
            Jan: 'Jan',
            Feb: 'Feb',
            Mar: 'Mar',
            Apr: 'Apr',
            May: 'May',
            Jun: 'Jun',
            Jul: 'Jul',
            Aug: 'Aug',
            Sep: 'Sep',
            Oct: 'Oct',
            Nov: 'Nov',
            Dec: 'Dec',
        },
        Excel: {
            Employee: {
                Title: 'The list of Employee',
                Sheet: 'Employee_list',
                FileName: 'Employee_list.xlsx',
            },
            Department: {
                Title: 'The list of Department',
                Sheet: 'Departmen_list',
                FileName: 'Department_list.xlsx',
            },
            Position: {
                Title: 'The list of Position',
                Sheet: 'Position_list',
                FileName: 'Position_list.xlsx',
            },
        },
        KeyName: {
            EmployeeCode: 'EmployeeCode',
            Id: 'Id',
            FullName: 'FullName',
            DateOfBirth: 'DateOfBirth',
            Gender: 'Gender',
            Email: 'Email',
            DepartmentName: 'Department Name',
            PositionName: 'Position Name',
            IdentityNumber: 'Identity Number',
            IdentityDate: 'Identity Date',
            IdentityPlace: 'Identity Place',
            Address: 'Address',
            PhoneNumberForm: 'Phone Number Form',
            PhoneNumber: 'Phone Number',
            Customer: 'Customer',
            Provider: 'Provider',
            LandlinePhone: 'Landline Phone',
            BankAccount: 'Bank Account',
            BankName: 'Bank Name',
            BankBranch: 'Bank Branch',
        },
    },
};
export default MISAResource;
